### NUMPY
* Stands for numerical python.
* Its is a python library used for working with arrays.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [4]:
# create 1D array

a1=np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [5]:
a1=np.array([1,2,3,4,5])
print(a1)
print(a1.ndim)

[1 2 3 4 5]
1


In [8]:
# create 2D array

a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)
print(a2.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [9]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)
print(a2.ndim)
print(a2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [10]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(a2.ndim)
print(a2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [12]:
# create 3D array

a3=np.array([[[1,2],[3,4],[5,6]]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[[1 2]
  [3 4]
  [5 6]]]
3
(1, 3, 2)


In [14]:
a3=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
4
(1, 2, 2, 2)


In [16]:
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.itemsize)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
4


### CREATING AN ARRAY USING RANGE METHOD
* np.array(range(start,end,step))
* np.array(range(start,end,step)).reshape(rows,columns)

In [20]:
a1=np.array(range(10))
print(a1)
print(a1.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [22]:
a1=np.array(range(10)).reshape(5,2)
print(a1)
print(a1.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
2


In [23]:
a1=np.array(range(10)).reshape(1,5,2)
print(a1)
print(a1.ndim)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
3


In [24]:
a1=np.array(range(10)).reshape(2,5,1)
print(a1)
print(a1.ndim)

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]
3


In [26]:
a1=np.array(range(10,40)).reshape(5,6)
print(a1)
print(a1.ndim)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]
2


In [27]:
a1=np.array(range(1,40,2)).reshape(5,4)
print(a1)
print(a1.ndim)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]
2


#### ZERO MATRIX

In [32]:
z=np.zeros((5,5))
print(z)
print(z[1][1])
print(type(z[1][1]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
0.0
<class 'numpy.float64'>


In [36]:
z=np.zeros((5,5),dtype='int')
print(z)
print(z[1][1])
print(type(z[1][1]))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
<class 'numpy.int32'>


#### ONES MATRIX

In [37]:
one=np.ones((5,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
one=np.ones((5,4),dtype=int)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [39]:
print(one*5)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [40]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [44]:
r=np.random.randint(10)
r

2

In [43]:
r=np.random.randint(10,20)
r

16

In [46]:
r=np.random.randint(10,20,5)
print(r)

[19 12 10 14 11]


In [47]:
r=np.random.randint(10,40,20).reshape(5,4)
print(r)

[[34 34 30 39]
 [35 19 23 23]
 [16 34 30 30]
 [16 23 19 32]
 [16 33 28 26]]


In [48]:
r=np.random.randint(10,40,(6,5))
print(r)

[[17 19 13 30 37]
 [18 17 11 20 17]
 [31 17 25 36 13]
 [30 21 37 13 16]
 [12 21 10 34 25]
 [29 19 33 21 33]]


In [49]:
np.random.random()

0.5086965747241595

In [51]:
np.random.random((2,3))

array([[0.0905373 , 0.35111456, 0.25790024],
       [0.62050034, 0.93461693, 0.65284621]])

In [52]:
print(np.log(1))

0.0


In [53]:
print(np.mean)

<function mean at 0x000002402B66C5E0>
